### PR TITLE
Support for cortex 2

### PR DESCRIPTION
**Pull request by Nick011**
Adds methods for new api endpoints available in cortex2 for organization and user management.

### CODE REVIEW

**Comment by theY4Kman** [comment]
bump for totally vain reasons — i wanna get rid of the `pip install git+git://github.com/usePF/Cortex4py#Cortex4py` line from a requirements.txt :P

**Comment by nadouani** [comment]
Hello guys, We are sorry for that, we were not aware you were working on this when we revamped the library.

Next time, let us know about what you wanna work on.

It's also a bit our fault because we didn't create the github issues related to the rewrite of the library

**Comment by nadouani** [comment]
Hello @Nick011 This PR is really outdated and targets the old version of Cortex4py.

I can include manually, the change made on `fix(exceptions): don't swallow them.`

**Comment by nadouani** [comment]
@Nick011 you can also, create a dedicated PR for that simple fix ;)

**Pull request closed without merging**
